apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  containers:
    -
      image: bitnami/tomcat
      name: tomcat
      ports:
        -
          containerPort: 8080
          name: http
          protocol: TCP
